version: '3.7'

services:

  rabbitmq:
    image: rabbitmq

  redis:
    image: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
          - discovery.type=single-node
    volumes: 
      - esdata:/usr/share/elasticsearch/data

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ./src/services/catalog/Catalog.API
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
  
    
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ./src/Services/Basket/Basket.API
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - redis
  


  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: ./src/ApiGateways/ApiGw-Base/OcelotApiGw
      dockerfile: Dockerfile
    volumes: 
      - ./src/services/ApiGateways/ApiGw-Base/Config:/app/configuration
     
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: src/Services/Ordering/Ordering.API
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
     

volumes:
  esdata:
    driver:
      local
   

 


