version: '3.7'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ./src/services/catalog/Catalog.API
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq


  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: ./src/ApiGateways/ApiGw-Base/OcelotApiGw
      dockerfile: Dockerfile
    volumes: 
      - ./src/services/ApiGateways/ApiGw-Base/Config:/app/configuration
     
      
   

 