version: '3.7'

services:

  rabbitmq:
    image: rabbitmq

  redis:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ./src/services/catalog/Catalog.API
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
  
    
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ./src/Services/Basket/Basket.API
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - redis
  


  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: ./src/ApiGateways/ApiGw-Base/OcelotApiGw
      dockerfile: Dockerfile
    volumes: 
      - ./src/services/ApiGateways/ApiGw-Base/Config:/app/configuration
     
      
   

 

